"""empty message

Revision ID: 4ce60df3537a
Revises: 3ff86b0675f1
Create Date: 2023-06-12 13:41:42.678678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce60df3537a'
down_revision = '3ff86b0675f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
