"""empty message

Revision ID: d07ef578504d
Revises: 7853d0846c4a
Create Date: 2023-04-27 17:54:21.438578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd07ef578504d'
down_revision = '7853d0846c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
